# Generated by Django 5.2.8 on 2025-11-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_animal_image_url_animal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='featured',
            field=models.BooleanField(default=False, help_text='Mark this animal as featured'),
        ),
    ]
